#!/bin/bash
#$ -V ## pass all environment variables to the job, VERY IMPORTANT
#$ -N addRG ## job name
#$ -S /bin/bash ## shell where it will run this job
#$ -cwd ## Execute the job from the current working directory
#$ -pe multi 2
#$ -m e
cd /storage/home/users/pjt6/fly_selective_sweeps
#export PATH=/shelf/apps/pjt6/conda/envs/trinity/bin/$PATH

#export PATH=/shelf/apps/pjt6/conda/envs/picard/bin/$PATH

conda activate picard

java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s100_sorted_marked.bam O=./bams/s100_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s100 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s101_sorted_marked.bam O=./bams/s101_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s101 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s102_sorted_marked.bam O=./bams/s102_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s102 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s104_sorted_marked.bam O=./bams/s104_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s104 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s105_sorted_marked.bam O=./bams/s105_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s105 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s106_sorted_marked.bam O=./bams/s106_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s106 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s107_sorted_marked.bam O=./bams/s107_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s107 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s108_sorted_marked.bam O=./bams/s108_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s108 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s109_sorted_marked.bam O=./bams/s109_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s109 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s110_sorted_marked.bam O=./bams/s110_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s110 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s111_sorted_marked.bam O=./bams/s111_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s111 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s112_sorted_marked.bam O=./bams/s112_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s112 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s113_sorted_marked.bam O=./bams/s113_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s113 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s114_sorted_marked.bam O=./bams/s114_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s114 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s115_sorted_marked.bam O=./bams/s115_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s115 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s116_sorted_marked.bam O=./bams/s116_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s116 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s117_sorted_marked.bam O=./bams/s117_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s117 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s119_sorted_marked.bam O=./bams/s119_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s119 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s11_sorted_marked.bam O=./bams/s11_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s11 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s121_sorted_marked.bam O=./bams/s121_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s121 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s122_sorted_marked.bam O=./bams/s122_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s122 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s123_sorted_marked.bam O=./bams/s123_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s123 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s124_sorted_marked.bam O=./bams/s124_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s124 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s125_sorted_marked.bam O=./bams/s125_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s125 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s126_sorted_marked.bam O=./bams/s126_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s126 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s127_sorted_marked.bam O=./bams/s127_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s127 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s128_sorted_marked.bam O=./bams/s128_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s128 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s129_sorted_marked.bam O=./bams/s129_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s129 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s12_sorted_marked.bam O=./bams/s12_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s12 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s130_sorted_marked.bam O=./bams/s130_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s130 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s131_sorted_marked.bam O=./bams/s131_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s131 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s132_sorted_marked.bam O=./bams/s132_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s132 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s133_sorted_marked.bam O=./bams/s133_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s133 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s134_sorted_marked.bam O=./bams/s134_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s134 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s135_sorted_marked.bam O=./bams/s135_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s135 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s136_sorted_marked.bam O=./bams/s136_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s136 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s139_sorted_marked.bam O=./bams/s139_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s139 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s13_sorted_marked.bam O=./bams/s13_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s13 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s140_sorted_marked.bam O=./bams/s140_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s140 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s141_sorted_marked.bam O=./bams/s141_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s141 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s142_sorted_marked.bam O=./bams/s142_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s142 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s143_sorted_marked.bam O=./bams/s143_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s143 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s144_sorted_marked.bam O=./bams/s144_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s144 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s145_sorted_marked.bam O=./bams/s145_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s145 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s146_sorted_marked.bam O=./bams/s146_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s146 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s147_sorted_marked.bam O=./bams/s147_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s147 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s148_sorted_marked.bam O=./bams/s148_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s148 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s149_sorted_marked.bam O=./bams/s149_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s149 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s151_sorted_marked.bam O=./bams/s151_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s151 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s154_sorted_marked.bam O=./bams/s154_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s154 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s155_sorted_marked.bam O=./bams/s155_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s155 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s156_sorted_marked.bam O=./bams/s156_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s156 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s157_sorted_marked.bam O=./bams/s157_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s157 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s158_sorted_marked.bam O=./bams/s158_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s158 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s159_sorted_marked.bam O=./bams/s159_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s159 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s160_sorted_marked.bam O=./bams/s160_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s160 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s161_sorted_marked.bam O=./bams/s161_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s161 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s162_sorted_marked.bam O=./bams/s162_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s162 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s163_sorted_marked.bam O=./bams/s163_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s163 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s164_sorted_marked.bam O=./bams/s164_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s164 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s165_sorted_marked.bam O=./bams/s165_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s165 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s17_sorted_marked.bam O=./bams/s17_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s17 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s18_sorted_marked.bam O=./bams/s18_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s18 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s1_sorted_marked.bam O=./bams/s1_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s1 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s21_sorted_marked.bam O=./bams/s21_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s21 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s24_sorted_marked.bam O=./bams/s24_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s24 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s25_sorted_marked.bam O=./bams/s25_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s25 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s27_sorted_marked.bam O=./bams/s27_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s27 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s29_sorted_marked.bam O=./bams/s29_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s29 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s30_sorted_marked.bam O=./bams/s30_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s30 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s31_sorted_marked.bam O=./bams/s31_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s31 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s32_sorted_marked.bam O=./bams/s32_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s32 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s33_sorted_marked.bam O=./bams/s33_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s33 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s34_sorted_marked.bam O=./bams/s34_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s34 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s35_sorted_marked.bam O=./bams/s35_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s35 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s37_sorted_marked.bam O=./bams/s37_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s37 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s39_sorted_marked.bam O=./bams/s39_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s39 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s3_sorted_marked.bam O=./bams/s3_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s3 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s40_sorted_marked.bam O=./bams/s40_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s40 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s42_sorted_marked.bam O=./bams/s42_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s42 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s43_sorted_marked.bam O=./bams/s43_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s43 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s46_sorted_marked.bam O=./bams/s46_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s46 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s47_sorted_marked.bam O=./bams/s47_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s47 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s48_sorted_marked.bam O=./bams/s48_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s48 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s49_sorted_marked.bam O=./bams/s49_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s49 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s50_sorted_marked.bam O=./bams/s50_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s50 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s51_sorted_marked.bam O=./bams/s51_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s51 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s53_sorted_marked.bam O=./bams/s53_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s53 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s54_sorted_marked.bam O=./bams/s54_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s54 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s55_sorted_marked.bam O=./bams/s55_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s55 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s56_sorted_marked.bam O=./bams/s56_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s56 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s57_sorted_marked.bam O=./bams/s57_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s57 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s58_sorted_marked.bam O=./bams/s58_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s58 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s59_sorted_marked.bam O=./bams/s59_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s59 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s5_sorted_marked.bam O=./bams/s5_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s5 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s60_sorted_marked.bam O=./bams/s60_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s60 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s61_sorted_marked.bam O=./bams/s61_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s61 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s62_sorted_marked.bam O=./bams/s62_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s62 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s63_sorted_marked.bam O=./bams/s63_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s63 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s64_sorted_marked.bam O=./bams/s64_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s64 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s67_sorted_marked.bam O=./bams/s67_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s67 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s68_sorted_marked.bam O=./bams/s68_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s68 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s69_sorted_marked.bam O=./bams/s69_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s69 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s6_sorted_marked.bam O=./bams/s6_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s6 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s70_sorted_marked.bam O=./bams/s70_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s70 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s72_sorted_marked.bam O=./bams/s72_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s72 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s73_sorted_marked.bam O=./bams/s73_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s73 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s74_sorted_marked.bam O=./bams/s74_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s74 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s76_sorted_marked.bam O=./bams/s76_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s76 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s77_sorted_marked.bam O=./bams/s77_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s77 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s78_sorted_marked.bam O=./bams/s78_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s78 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s7_sorted_marked.bam O=./bams/s7_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s7 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s80_sorted_marked.bam O=./bams/s80_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s80 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s81_sorted_marked.bam O=./bams/s81_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s81 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s82_sorted_marked.bam O=./bams/s82_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s82 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s83_sorted_marked.bam O=./bams/s83_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s83 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s8_sorted_marked.bam O=./bams/s8_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s8 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s90_sorted_marked.bam O=./bams/s90_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s90 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s92_sorted_marked.bam O=./bams/s92_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s92 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s95_sorted_marked.bam O=./bams/s95_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s95 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s96_sorted_marked.bam O=./bams/s96_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s96 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s98_sorted_marked.bam O=./bams/s98_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s98 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
java -Xmx50G -jar /shelf/apps/pjt6/conda/envs/picard/share/picard-2.18.29-0/picard.jar  AddOrReplaceReadGroups I=./bams/s9_sorted_marked.bam O=./bams/s9_sorted_marked_RG.bam RGLB=lib1 RGPL=Illumina RGPU=flowcell:Sample RGSM=s9 SO=coordinate CREATE_INDEX=true  VALIDATION_STRINGENCY=LENIENT
