
cd /storage/home/users/pjt6/fly_selective_sweeps/


gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s156_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s156.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s76_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s76.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s146_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s146.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s67_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s67.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s145_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s145.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s122_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s122.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s21_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s21.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s39_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s39.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s70_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s70.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s60_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s60.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s72_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s72.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s29_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s29.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s58_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s58.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s162_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s162.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s61_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s61.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s96_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s96.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s49_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s49.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s135_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s135.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s27_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s27.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s123_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s123.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s81_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s81.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s136_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s136.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s163_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s163.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s43_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s43.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s33_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s33.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s165_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s165.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s80_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s80.vcf
gatk --java-options '-Xmx120G' HaplotypeCaller -R /storage/home/users/pjt6/fly_selective_sweeps/genome/GCA_000001765.3_Dpse_4.0_genomic.fna -I /storage/home/users/pjt6/fly_selective_sweeps/bams/s50_sorted_marked_RG.bam -O /storage/home/users/pjt6/fly_selective_sweeps/vcfs/s50.vcf
